default:
  interruptible: true

stages:
  - test

variables:
  npm_config_fund: "false"

.test:
  stage: test
  script:
    - git submodule update --init
    - npm install
    - npm run rebuild
    - npm run lint
    - npm test

test:linux:node16:
  extends: .test
  image: node:16-buster

test:linux:node17:
  extends: .test
  image: node:17-buster

test:windows:
  extends: .test
  before_script:
    - choco install python2 --pre -y
  tags:
    - shared-windows
    - windows
    - windows-1809
